name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2 using rsync
      run: |
        rsync -avz -e "ssh -i /home/runner/.ssh/deploy_key" ./ ec2-user@13.60.6.61:/home/ec2-user
      env:
        EC2_USER: ec2-user
        EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }}
        REMOTE_PATH: /home/ec2-user
